# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.label_showQRcode = QtWidgets.QLabel(Form)
        self.label_showQRcode.setGeometry(QtCore.QRect(500, 50, 500, 500))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_showQRcode.sizePolicy().hasHeightForWidth())
        self.label_showQRcode.setSizePolicy(sizePolicy)
        self.label_showQRcode.setText("")
        self.label_showQRcode.setTextFormat(QtCore.Qt.AutoText)
        self.label_showQRcode.setPixmap(QtGui.QPixmap(":/resource/img/1010.png"))
        self.label_showQRcode.setAlignment(QtCore.Qt.AlignCenter)
        self.label_showQRcode.setObjectName("label_showQRcode")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 471, 581))
        self.layoutWidget.setObjectName("layoutWidget")
        self.boxinfo = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.boxinfo.setContentsMargins(0, 0, 0, 0)
        self.boxinfo.setObjectName("boxinfo")
        self.label_displaytime = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_displaytime.setFont(font)
        self.label_displaytime.setAlignment(QtCore.Qt.AlignCenter)
        self.label_displaytime.setObjectName("label_displaytime")
        self.boxinfo.addWidget(self.label_displaytime)
        self.label_displaynumber = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_displaynumber.setFont(font)
        self.label_displaynumber.setAlignment(QtCore.Qt.AlignCenter)
        self.label_displaynumber.setObjectName("label_displaynumber")
        self.boxinfo.addWidget(self.label_displaynumber)
        self.label_displaytemp = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_displaytemp.setFont(font)
        self.label_displaytemp.setAlignment(QtCore.Qt.AlignCenter)
        self.label_displaytemp.setObjectName("label_displaytemp")
        self.boxinfo.addWidget(self.label_displaytemp)
        self.label_displaystatus = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_displaystatus.setFont(font)
        self.label_displaystatus.setAlignment(QtCore.Qt.AlignCenter)
        self.label_displaystatus.setObjectName("label_displaystatus")
        self.boxinfo.addWidget(self.label_displaystatus)
        self.label_displayster = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_displayster.setFont(font)
        self.label_displayster.setAlignment(QtCore.Qt.AlignCenter)
        self.label_displayster.setObjectName("label_displayster")
        self.boxinfo.addWidget(self.label_displayster)
        self.label_displaylock = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_displaylock.setFont(font)
        self.label_displaylock.setAlignment(QtCore.Qt.AlignCenter)
        self.label_displaylock.setObjectName("label_displaylock")
        self.boxinfo.addWidget(self.label_displaylock)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_displaytime.setText(_translate("Form", "时间显示"))
        self.label_displaynumber.setText(_translate("Form", "箱柜号:1010"))
        self.label_displaytemp.setText(_translate("Form", "温度显示"))
        self.label_displaystatus.setText(_translate("Form", "用户显示"))
        self.label_displayster.setText(_translate("Form", "紫外线状态"))
        self.label_displaylock.setText(_translate("Form", "门锁状态"))
import resource
