# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.label_showQRcode = QtWidgets.QLabel(Form)
        self.label_showQRcode.setGeometry(QtCore.QRect(400, 40, 500, 500))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_showQRcode.sizePolicy().hasHeightForWidth())
        self.label_showQRcode.setSizePolicy(sizePolicy)
        self.label_showQRcode.setText("")
        self.label_showQRcode.setTextFormat(QtCore.Qt.AutoText)
        self.label_showQRcode.setPixmap(QtGui.QPixmap(":/resource/img/1010.png"))
        self.label_showQRcode.setAlignment(QtCore.Qt.AlignCenter)
        self.label_showQRcode.setObjectName("label_showQRcode")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(30, 60, 331, 481))
        self.widget.setObjectName("widget")
        self.boxinfo = QtWidgets.QVBoxLayout(self.widget)
        self.boxinfo.setContentsMargins(0, 0, 0, 0)
        self.boxinfo.setObjectName("boxinfo")
        self.label_showtime = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_showtime.setFont(font)
        self.label_showtime.setAlignment(QtCore.Qt.AlignCenter)
        self.label_showtime.setObjectName("label_showtime")
        self.boxinfo.addWidget(self.label_showtime)
        self.label_shownumber = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_shownumber.setFont(font)
        self.label_shownumber.setAlignment(QtCore.Qt.AlignCenter)
        self.label_shownumber.setObjectName("label_shownumber")
        self.boxinfo.addWidget(self.label_shownumber)
        self.label_showtemp = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_showtemp.setFont(font)
        self.label_showtemp.setAlignment(QtCore.Qt.AlignCenter)
        self.label_showtemp.setObjectName("label_showtemp")
        self.boxinfo.addWidget(self.label_showtemp)
        self.label_showster = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_showster.setFont(font)
        self.label_showster.setAlignment(QtCore.Qt.AlignCenter)
        self.label_showster.setObjectName("label_showster")
        self.boxinfo.addWidget(self.label_showster)
        self.label_showlock = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_showlock.setFont(font)
        self.label_showlock.setAlignment(QtCore.Qt.AlignCenter)
        self.label_showlock.setObjectName("label_showlock")
        self.boxinfo.addWidget(self.label_showlock)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_showtime.setText(_translate("Form", "时间显示"))
        self.label_shownumber.setText(_translate("Form", "箱柜号:1010"))
        self.label_showtemp.setText(_translate("Form", "温度显示"))
        self.label_showster.setText(_translate("Form", "紫外线状态"))
        self.label_showlock.setText(_translate("Form", "门锁状态"))
import resource
